### ISSUE TITLE
Popup Box not dismissing on it's own

### ISSUE THREAD

**Issue by the-war-horse** [AlexFielder/MyFirstInventorAddin#12]
```
Clipboard.SetText(TextBox6.Text)
        'CreateObject("WScript.Shell").PopUp("Copied to Clipboard", 1)
```

It doesn't self dismiss after 1 second as it should.

**Comment by AlexFielder** [comment]
You could forego using WScript and use Inventor's status bar instead, I've got a couple of methods I've been using for a while which will allow you to do just that:

```VB
''' <summary>
''' Updates the statusbar with a percentage value
''' </summary>
''' <param name="percent"></param>
''' <param name="Message"></param>
''' <remarks></remarks>
Private Sub UpdateStatusBar(ByVal percent As Double, ByVal Message As String)
     m_inventorApplication.StatusBarText = Message + " (" + percent.ToString("P1") + ")"
End Sub
''' <summary>
''' updates the statusbar with a string value.
''' </summary>
''' <param name="Message"></param>
''' <remarks></remarks>
Private Sub UpdateStatusBar(ByVal Message As String)
    m_inventorApplication.StatusBarText = Message
End Sub
```

The m_inventorApplication would need to be pointed to the AddinGlobal.Inventorapp but otherwise they could remain unchanged.

You could even go so far as to use them to alert the user when properties have been updated as we are currently only writing that information to the log file.

**Comment by the-war-horse** [comment]
OK this is cool. I'll try this out asap.

**Comment by AlexFielder** [comment]
Closing this as we use the UpdateStatusbar method now; pending of course #14 gets fixed...
